#!/bin/bash

echo "🔒 TESTING PUBLICATION VISIBILITY LOGIC"
echo "========================================"

echo "📋 Test Plan:"
echo "============="
echo "1. Test public publications (should show to everyone)"
echo "2. Test friends publications (should show to friends only)"
echo "3. Test private publications (should show to author only)"
echo ""

echo "🔧 Prerequisites:"
echo "================="
echo "1. Get JWT token from auth service"
echo "2. Create test publications with different visibilities"
echo "3. Verify filtering works correctly"
echo ""

echo "Step 1: Get JWT Token"
echo "====================="
echo "curl -X POST http://54.146.237.63:3001/api/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"aura@gmail.com\",\"password\":\"@Aura1234\"}'"
echo ""
echo "# Copy the token from response and use in TOKEN variable below"
echo ""

echo "Step 2: Create Test Publications"
echo "==============================="

echo "# Create PUBLIC publication"
echo "curl -X POST http://54.146.237.63:3002/api/v1/publications \\"
echo "  -H 'Authorization: Bearer \$TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"content\":\"This is a PUBLIC post\",\"type\":\"text\",\"visibility\":\"public\"}'"
echo ""

echo "# Create FRIENDS publication"
echo "curl -X POST http://54.146.237.63:3002/api/v1/publications \\"
echo "  -H 'Authorization: Bearer \$TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"content\":\"This is a FRIENDS-only post\",\"type\":\"text\",\"visibility\":\"friends\"}'"
echo ""

echo "# Create PRIVATE publication"
echo "curl -X POST http://54.146.237.63:3002/api/v1/publications \\"
echo "  -H 'Authorization: Bearer \$TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"content\":\"This is a PRIVATE post\",\"type\":\"text\",\"visibility\":\"private\"}'"
echo ""

echo "Step 3: Test Visibility Filtering"
echo "================================="

echo "# Get all publications (should apply visibility filters)"
echo "curl -X GET http://54.146.237.63:3002/api/v1/publications?page=1&limit=10 \\"
echo "  -H 'Authorization: Bearer \$TOKEN'"
echo ""

echo "Expected Results:"
echo "================"
echo "✅ For the author: Should see ALL publications (public, friends, private)"
echo "✅ For other users: Should see only PUBLIC publications"
echo "✅ For friends: Should see PUBLIC + FRIENDS publications"
echo ""

echo "Step 4: Check Logs"
echo "=================="
echo "pm2 logs social-service --lines 100"
echo ""
echo "Look for these log entries:"
echo "- '🔒 Aplicando filtros de visibilidad para usuario: USER_ID'"
echo "- '👥 Amigos del usuario: [...]'"
echo "- '🔍 Filtros de visibilidad aplicados: {...}'"
echo "- '✅ Encontradas X publicaciones (después de filtros de visibilidad)'"
echo ""

echo "🚨 Troubleshooting:"
echo "==================="
echo "If visibility filtering is not working:"
echo ""
echo "1. Check that currentUserId is being passed correctly:"
echo "   - Look for '👤 GetPublications - user from token: {...}'"
echo "   - Should contain user ID"
echo ""
echo "2. Check that UserProfile exists and has friends data:"
echo "   - Check if user_profiles table has data"
echo "   - friends column should be JSON array"
echo ""
echo "3. Restart service if needed:"
echo "   pm2 restart social-service"
echo ""

echo "📊 Database Verification:"
echo "========================="
echo "# Check publications in database"
echo "mysql -u root -p social_db -e \"SELECT id, user_id, SUBSTRING(content,1,30) as content, visibility, created_at FROM posts ORDER BY created_at DESC LIMIT 10;\""
echo ""
echo "# Check user profiles and friends"
echo "mysql -u root -p social_db -e \"SELECT user_id, SUBSTRING(friends,1,50) as friends FROM user_profiles;\""
echo ""

echo "✅ BACKEND VISIBILITY LOGIC NOW IMPLEMENTED"
echo "=========================================="
echo "The backend now properly filters publications based on:"
echo "- visibility: 'public' → Everyone can see"
echo "- visibility: 'friends' → Only friends can see"
echo "- visibility: 'private' → Only author can see"
echo ""
echo "Flutter app should now show correct publications based on user relationships!"